language: ruby
rvm:
- 2.4.2
notifications:
  slack:
    secure: tamokVveiWDMjuHRhK3X8KmUgsHwldmRC7UiPJ52Vsj7YappUGM+edjSBUW/4+ief78xfVu5JajQ2d2uWhDaecQ/iGawLIfrURKsPdG2Ai+V0sl4tx8VTIk6WkzjWT5fKSSVQOrzf8MSThkur9+K0iwBAOC9lOSXf9QIJzgIMOPbjq+GA+/csmkjDUL1vwDTujxYZz0bPtLLg5hbJX3B06DnB+ccN0v4xTpA82bkBIEiwnO5xbBGq8/Z1DdU+9TQWPA2RXgXQvGlKvdvChka9mQ4Cq7prmwKyfGdwzjFGcC1yqV/Z1bvWeUoepWuoH5lhuzOSZZ4wHUMEMI+9eAXceUo3Ter3UIGkNWQeji5R0QQbGz9a8tJY56pF4Kug/2Uo+i4VUj+KkEXhl+CabqK4S0llSwOfNRLhrYChJnvgXLgT8cX/RlHaNKQTZPVr+xvgtHoUiOtp9vJE8d79vSRG2ElYr379o3z8bjsjAM9qjt4MPoofngOaQfPWRSbPLPdVC/ENcJo+L+Jab0lVePFDY3/Au5VGAiFIP2Ix8DAhkIa7d/O96AqM+yaFm8uGF84NiqYBp99lohOn8n9eLStW3GqgvOiKbGBBtQeXEbG47SRv2DekeTDMmwmhUgswGVMCE+NzZ6ud88JumdTDhm+GpeBUULJAf+3X0MX39c5uH0=
